# -*- coding: utf-8 -*-
"""Data Science Summative - Sanchit and Aarnav

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWK_RVkKEg1CHtMShkrJBTj0zedwWaRj
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/ghg-emissions-by-sector.csv")

df.head()

df.isnull().sum()

df.fillna(method="bfill")

df.duplicated().sum()

df.info()

df.describe()

#Analyze Data

df_filtered = df[df['Entity'] == 'World']
df_filtered = df_filtered[df_filtered['Year'] >= 1990]
df_subset = df_filtered[['Year', 'Entity', 'Greenhouse gas emissions from agriculture', 'Greenhouse gas emissions from industry', 'Greenhouse gas emissions from transport', 'Greenhouse gas emissions from electricity and heat']]
df_subset.head()

import matplotlib.pyplot as plt

# Define the columns for greenhouse gas emissions
emission_columns = [
    'Greenhouse gas emissions from agriculture',
    'Greenhouse gas emissions from industry',
    'Greenhouse gas emissions from transport',
    'Greenhouse gas emissions from electricity and heat'
]

# Create a figure and an axes object for the plot
plt.figure(figsize=(12, 8))

# Plot each emission column against 'Year'
for column in emission_columns:
    # Convert emissions to Gigatons (1e9) for better readability on the y-axis
    plt.plot(df_subset['Year'], df_subset[column] / 1e9, label=column.replace('Greenhouse gas emissions from ', ''))

# Add title and labels
plt.title('Global GHG Emissions Trends by Sector (1990 onwards)')
plt.xlabel('Year')
plt.ylabel('GHG Emissions (Gigatons)')

# Add a legend to the plot
plt.legend(title='Emission Sector')

# Display the plot
plt.grid(True)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.scatterplot(
    x=df_subset['Greenhouse gas emissions from agriculture'] / 1e9,
    y=df_subset['Greenhouse gas emissions from transport'] / 1e9
)

plt.title('Relationship between Agriculture and Transport GHG Emissions (World)')
plt.xlabel('Greenhouse Gas Emissions from Agriculture (Gigatons)')
plt.ylabel('Greenhouse Gas Emissions from Transport (Gigatons)')
plt.grid(True)
plt.show()

# Define the columns for greenhouse gas emissions to be compared
emission_columns_to_compare = [
    'Greenhouse gas emissions from agriculture',
    'Greenhouse gas emissions from industry',
    'Greenhouse gas emissions from transport',
    'Greenhouse gas emissions from electricity and heat'
]

# Select specific years for comparison. Assuming max year in data is 2022.
selected_years = [1990, 2000, 2010, 2022]

# Filter df_subset for the selected years
df_comparison_years = df_subset[df_subset['Year'].isin(selected_years)].copy()

# Melt the dataframe to long format for easier plotting with seaborn
df_melted_comparison = df_comparison_years.melt(
    id_vars=['Year'],
    value_vars=emission_columns_to_compare,
    var_name='Emission Sector',
    value_name='GHG Emissions'
)

# Convert emissions to Gigatons for better readability on the y-axis
df_melted_comparison['GHG Emissions (Gigatons)'] = df_melted_comparison['GHG Emissions'] / 1e9

# Clean up sector names for better legend/labels
df_melted_comparison['Emission Sector'] = df_melted_comparison['Emission Sector'].str.replace('Greenhouse gas emissions from ', '')

plt.figure(figsize=(14, 8))

sns.barplot(
    x='Emission Sector',
    y='GHG Emissions (Gigatons)',
    hue='Year',
    data=df_melted_comparison,
    palette='viridis'
)

plt.title('Global GHG Emissions by Sector for Selected Years (Gigatons)')
plt.xlabel('Emission Sector')
plt.ylabel('GHG Emissions (Gigatons)')
plt.legend(title='Year')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

